# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antientropy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61ntientropy.proto\x12\x02\x61\x65\")\n\x0b\x42ucketEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"J\n\x0bSyncRequest\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x1f\n\x06\x62ucket\x18\x03 \x03(\x0b\x32\x0f.ae.BucketEntry\"=\n\x0cSyncResponse\x12\x0c\n\x04same\x18\x01 \x01(\x08\x12\x1f\n\x06\x62ucket\x18\x02 \x03(\x0b\x32\x0f.ae.BucketEntry2:\n\x0b\x41ntiEntropy\x12+\n\x04Sync\x12\x0f.ae.SyncRequest\x1a\x10.ae.SyncResponse\"\x00\x42&\n\x13io.grpc.examples.aeB\x07\x41\x45ProtoP\x01\xa2\x02\x03HLWb\x06proto3')



_BUCKETENTRY = DESCRIPTOR.message_types_by_name['BucketEntry']
_SYNCREQUEST = DESCRIPTOR.message_types_by_name['SyncRequest']
_SYNCRESPONSE = DESCRIPTOR.message_types_by_name['SyncResponse']
BucketEntry = _reflection.GeneratedProtocolMessageType('BucketEntry', (_message.Message,), {
  'DESCRIPTOR' : _BUCKETENTRY,
  '__module__' : 'antientropy_pb2'
  # @@protoc_insertion_point(class_scope:ae.BucketEntry)
  })
_sym_db.RegisterMessage(BucketEntry)

SyncRequest = _reflection.GeneratedProtocolMessageType('SyncRequest', (_message.Message,), {
  'DESCRIPTOR' : _SYNCREQUEST,
  '__module__' : 'antientropy_pb2'
  # @@protoc_insertion_point(class_scope:ae.SyncRequest)
  })
_sym_db.RegisterMessage(SyncRequest)

SyncResponse = _reflection.GeneratedProtocolMessageType('SyncResponse', (_message.Message,), {
  'DESCRIPTOR' : _SYNCRESPONSE,
  '__module__' : 'antientropy_pb2'
  # @@protoc_insertion_point(class_scope:ae.SyncResponse)
  })
_sym_db.RegisterMessage(SyncResponse)

_ANTIENTROPY = DESCRIPTOR.services_by_name['AntiEntropy']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023io.grpc.examples.aeB\007AEProtoP\001\242\002\003HLW'
  _BUCKETENTRY._serialized_start=25
  _BUCKETENTRY._serialized_end=66
  _SYNCREQUEST._serialized_start=68
  _SYNCREQUEST._serialized_end=142
  _SYNCRESPONSE._serialized_start=144
  _SYNCRESPONSE._serialized_end=205
  _ANTIENTROPY._serialized_start=207
  _ANTIENTROPY._serialized_end=265
# @@protoc_insertion_point(module_scope)
