# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antientropy.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61ntientropy.proto\x12\x02\x61\x65\"\x19\n\x17\x43reateMerkleTreeRequest\"\x1a\n\x18\x43reateMerkleTreeResponse\"C\n\x14\x41ppendEntriesRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"(\n\x15\x41ppendEntriesResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"$\n\x06KVPair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"F\n\x0bSyncRequest\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x1b\n\x07subtree\x18\x03 \x03(\x0b\x32\n.ae.KVPair\"<\n\x0cSyncResponse\x12\x0f\n\x07retcode\x18\x01 \x01(\x03\x12\x1b\n\x07subtree\x18\x02 \x03(\x0b\x32\n.ae.KVPair2\xd3\x01\n\x0b\x41ntiEntropy\x12+\n\x04Sync\x12\x0f.ae.SyncRequest\x1a\x10.ae.SyncResponse\"\x00\x12\x46\n\rAppendEntries\x12\x18.ae.AppendEntriesRequest\x1a\x19.ae.AppendEntriesResponse\"\x00\x12O\n\x10\x43reateMerkleTree\x12\x1b.ae.CreateMerkleTreeRequest\x1a\x1c.ae.CreateMerkleTreeResponse\"\x00\x42&\n\x13io.grpc.examples.aeB\x07\x41\x45ProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antientropy_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023io.grpc.examples.aeB\007AEProtoP\001\242\002\003HLW'
  _CREATEMERKLETREEREQUEST._serialized_start=25
  _CREATEMERKLETREEREQUEST._serialized_end=50
  _CREATEMERKLETREERESPONSE._serialized_start=52
  _CREATEMERKLETREERESPONSE._serialized_end=78
  _APPENDENTRIESREQUEST._serialized_start=80
  _APPENDENTRIESREQUEST._serialized_end=147
  _APPENDENTRIESRESPONSE._serialized_start=149
  _APPENDENTRIESRESPONSE._serialized_end=189
  _KVPAIR._serialized_start=191
  _KVPAIR._serialized_end=227
  _SYNCREQUEST._serialized_start=229
  _SYNCREQUEST._serialized_end=299
  _SYNCRESPONSE._serialized_start=301
  _SYNCRESPONSE._serialized_end=361
  _ANTIENTROPY._serialized_start=364
  _ANTIENTROPY._serialized_end=575
# @@protoc_insertion_point(module_scope)
