# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consistentHashing.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63onsistentHashing.proto\x12\x11\x63onsistentHashing\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\"\n\x0e\x44\x65leteResponse\x12\x10\n\x08\x65rrormsg\x18\x01 \x01(\t\"\x1c\n\x0e\x41\x64\x64NodeRequest\x12\n\n\x02ip\x18\x01 \x01(\t\"#\n\x0f\x41\x64\x64NodeResponse\x12\x10\n\x08\x65rrormsg\x18\x01 \x01(\t\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0bGetResponse\x12\r\n\x05value\x18\x02 \x01(\t\"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1f\n\x0bPutResponse\x12\x10\n\x08\x65rrormsg\x18\x01 \x01(\t2\x97\x03\n\x11\x43onsistentHashing\x12\x46\n\x03Get\x12\x1d.consistentHashing.GetRequest\x1a\x1e.consistentHashing.GetResponse\"\x00\x12\x46\n\x03Put\x12\x1d.consistentHashing.PutRequest\x1a\x1e.consistentHashing.PutResponse\"\x00\x12R\n\x07\x41\x64\x64Node\x12!.consistentHashing.AddNodeRequest\x1a\".consistentHashing.AddNodeResponse\"\x00\x12M\n\nRemoveNode\x12\x1d.consistentHashing.PutRequest\x1a\x1e.consistentHashing.PutResponse\"\x00\x12O\n\x06\x44\x65lete\x12 .consistentHashing.DeleteRequest\x1a!.consistentHashing.DeleteResponse\"\x00\x42\x30\n\x18io.grpc.examples.leveldbB\x0cLevelDBProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'consistentHashing_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030io.grpc.examples.leveldbB\014LevelDBProtoP\001\242\002\003HLW'
  _DELETEREQUEST._serialized_start=46
  _DELETEREQUEST._serialized_end=74
  _DELETERESPONSE._serialized_start=76
  _DELETERESPONSE._serialized_end=110
  _ADDNODEREQUEST._serialized_start=112
  _ADDNODEREQUEST._serialized_end=140
  _ADDNODERESPONSE._serialized_start=142
  _ADDNODERESPONSE._serialized_end=177
  _GETREQUEST._serialized_start=179
  _GETREQUEST._serialized_end=204
  _GETRESPONSE._serialized_start=206
  _GETRESPONSE._serialized_end=234
  _PUTREQUEST._serialized_start=236
  _PUTREQUEST._serialized_end=276
  _PUTRESPONSE._serialized_start=278
  _PUTRESPONSE._serialized_end=309
  _CONSISTENTHASHING._serialized_start=312
  _CONSISTENTHASHING._serialized_end=719
# @@protoc_insertion_point(module_scope)
