# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\x08\x64\x61tabase\"5\n\x11KeysToMoveRequest\x12\x10\n\x08startKey\x18\x01 \x01(\t\x12\x0e\n\x06\x65ndKey\x18\x02 \x01(\t\"$\n\x06KVpair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"7\n\x12KeysToMoveResponse\x12!\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x10.database.KVpair\"\r\n\x0b\x45mptyParams\"%\n\x13MemoryUsageResponse\x12\x0e\n\x06isHigh\x18\x01 \x01(\x08\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0bGetResponse\x12\r\n\x05value\x18\x02 \x01(\t\"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1f\n\x0bPutResponse\x12\x10\n\x08\x65rrormsg\x18\x01 \x01(\t2\x8e\x02\n\x08\x44\x61tabase\x12\x34\n\x03Get\x12\x14.database.GetRequest\x1a\x15.database.GetResponse\"\x00\x12\x34\n\x03Put\x12\x14.database.PutRequest\x1a\x15.database.PutResponse\"\x00\x12K\n\x11IsMemoryUsageHigh\x12\x15.database.EmptyParams\x1a\x1d.database.MemoryUsageResponse\"\x00\x12I\n\nKeysToMove\x12\x1b.database.KeysToMoveRequest\x1a\x1c.database.KeysToMoveResponse\"\x00\x42\x30\n\x18io.grpc.examples.leveldbB\x0cLevelDBProtoP\x01\xa2\x02\x03HLWb\x06proto3')



_KEYSTOMOVEREQUEST = DESCRIPTOR.message_types_by_name['KeysToMoveRequest']
_KVPAIR = DESCRIPTOR.message_types_by_name['KVpair']
_KEYSTOMOVERESPONSE = DESCRIPTOR.message_types_by_name['KeysToMoveResponse']
_EMPTYPARAMS = DESCRIPTOR.message_types_by_name['EmptyParams']
_MEMORYUSAGERESPONSE = DESCRIPTOR.message_types_by_name['MemoryUsageResponse']
_GETREQUEST = DESCRIPTOR.message_types_by_name['GetRequest']
_GETRESPONSE = DESCRIPTOR.message_types_by_name['GetResponse']
_PUTREQUEST = DESCRIPTOR.message_types_by_name['PutRequest']
_PUTRESPONSE = DESCRIPTOR.message_types_by_name['PutResponse']
KeysToMoveRequest = _reflection.GeneratedProtocolMessageType('KeysToMoveRequest', (_message.Message,), {
  'DESCRIPTOR' : _KEYSTOMOVEREQUEST,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:database.KeysToMoveRequest)
  })
_sym_db.RegisterMessage(KeysToMoveRequest)

KVpair = _reflection.GeneratedProtocolMessageType('KVpair', (_message.Message,), {
  'DESCRIPTOR' : _KVPAIR,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:database.KVpair)
  })
_sym_db.RegisterMessage(KVpair)

KeysToMoveResponse = _reflection.GeneratedProtocolMessageType('KeysToMoveResponse', (_message.Message,), {
  'DESCRIPTOR' : _KEYSTOMOVERESPONSE,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:database.KeysToMoveResponse)
  })
_sym_db.RegisterMessage(KeysToMoveResponse)

EmptyParams = _reflection.GeneratedProtocolMessageType('EmptyParams', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYPARAMS,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:database.EmptyParams)
  })
_sym_db.RegisterMessage(EmptyParams)

MemoryUsageResponse = _reflection.GeneratedProtocolMessageType('MemoryUsageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MEMORYUSAGERESPONSE,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:database.MemoryUsageResponse)
  })
_sym_db.RegisterMessage(MemoryUsageResponse)

GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUEST,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:database.GetRequest)
  })
_sym_db.RegisterMessage(GetRequest)

GetResponse = _reflection.GeneratedProtocolMessageType('GetResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETRESPONSE,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:database.GetResponse)
  })
_sym_db.RegisterMessage(GetResponse)

PutRequest = _reflection.GeneratedProtocolMessageType('PutRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUTREQUEST,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:database.PutRequest)
  })
_sym_db.RegisterMessage(PutRequest)

PutResponse = _reflection.GeneratedProtocolMessageType('PutResponse', (_message.Message,), {
  'DESCRIPTOR' : _PUTRESPONSE,
  '__module__' : 'database_pb2'
  # @@protoc_insertion_point(class_scope:database.PutResponse)
  })
_sym_db.RegisterMessage(PutResponse)

_DATABASE = DESCRIPTOR.services_by_name['Database']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030io.grpc.examples.leveldbB\014LevelDBProtoP\001\242\002\003HLW'
  _KEYSTOMOVEREQUEST._serialized_start=28
  _KEYSTOMOVEREQUEST._serialized_end=81
  _KVPAIR._serialized_start=83
  _KVPAIR._serialized_end=119
  _KEYSTOMOVERESPONSE._serialized_start=121
  _KEYSTOMOVERESPONSE._serialized_end=176
  _EMPTYPARAMS._serialized_start=178
  _EMPTYPARAMS._serialized_end=191
  _MEMORYUSAGERESPONSE._serialized_start=193
  _MEMORYUSAGERESPONSE._serialized_end=230
  _GETREQUEST._serialized_start=232
  _GETREQUEST._serialized_end=257
  _GETRESPONSE._serialized_start=259
  _GETRESPONSE._serialized_end=287
  _PUTREQUEST._serialized_start=289
  _PUTREQUEST._serialized_end=329
  _PUTRESPONSE._serialized_start=331
  _PUTRESPONSE._serialized_end=362
  _DATABASE._serialized_start=365
  _DATABASE._serialized_end=635
# @@protoc_insertion_point(module_scope)
