# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\x08\x64\x61tabase\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\"\n\x0e\x44\x65leteResponse\x12\x10\n\x08\x65rrormsg\x18\x01 \x01(\t\"5\n\x11KeysToMoveRequest\x12\x10\n\x08startKey\x18\x01 \x01(\t\x12\x0e\n\x06\x65ndKey\x18\x02 \x01(\t\"$\n\x06KVpair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"7\n\x12KeysToMoveResponse\x12!\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x10.database.KVpair\"\r\n\x0b\x45mptyParams\"%\n\x13MemoryUsageResponse\x12\x0e\n\x06isHigh\x18\x01 \x01(\x08\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0bGetResponse\x12\r\n\x05value\x18\x02 \x01(\t\"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1f\n\x0bPutResponse\x12\x10\n\x08\x65rrormsg\x18\x01 \x01(\t2\xcd\x02\n\x08\x44\x61tabase\x12\x34\n\x03Get\x12\x14.database.GetRequest\x1a\x15.database.GetResponse\"\x00\x12\x34\n\x03Put\x12\x14.database.PutRequest\x1a\x15.database.PutResponse\"\x00\x12K\n\x11IsMemoryUsageHigh\x12\x15.database.EmptyParams\x1a\x1d.database.MemoryUsageResponse\"\x00\x12I\n\nKeysToMove\x12\x1b.database.KeysToMoveRequest\x1a\x1c.database.KeysToMoveResponse\"\x00\x12=\n\x06\x44\x65lete\x12\x17.database.DeleteRequest\x1a\x18.database.DeleteResponse\"\x00\x42\x30\n\x18io.grpc.examples.leveldbB\x0cLevelDBProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030io.grpc.examples.leveldbB\014LevelDBProtoP\001\242\002\003HLW'
  _DELETEREQUEST._serialized_start=28
  _DELETEREQUEST._serialized_end=56
  _DELETERESPONSE._serialized_start=58
  _DELETERESPONSE._serialized_end=92
  _KEYSTOMOVEREQUEST._serialized_start=94
  _KEYSTOMOVEREQUEST._serialized_end=147
  _KVPAIR._serialized_start=149
  _KVPAIR._serialized_end=185
  _KEYSTOMOVERESPONSE._serialized_start=187
  _KEYSTOMOVERESPONSE._serialized_end=242
  _EMPTYPARAMS._serialized_start=244
  _EMPTYPARAMS._serialized_end=257
  _MEMORYUSAGERESPONSE._serialized_start=259
  _MEMORYUSAGERESPONSE._serialized_end=296
  _GETREQUEST._serialized_start=298
  _GETREQUEST._serialized_end=323
  _GETRESPONSE._serialized_start=325
  _GETRESPONSE._serialized_end=353
  _PUTREQUEST._serialized_start=355
  _PUTREQUEST._serialized_end=395
  _PUTRESPONSE._serialized_start=397
  _PUTRESPONSE._serialized_end=428
  _DATABASE._serialized_start=431
  _DATABASE._serialized_end=764
# @@protoc_insertion_point(module_scope)
